version: "3.8"
services:
  mc:
    restart: "no"
    build: "minecraft-server"
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    volumes:
      - ${PWD}/volumes/mc:/papermc
    environment:
      - MC_VERSION=1.18
      - PAPER_BUILD=66
      - MC_RAM=1G
    stdin_open: true
    tty: true